<!-- This is the code for the src\components\mappledir\mapdir\mapContainer.vue -->

<template>
  <div id="globeDiv" class="map-container"></div>
</template>

<script>
import * as am5 from "@amcharts/amcharts5";
import * as am5map from "@amcharts/amcharts5/map";
import am5geodata_worldLow from "@amcharts/amcharts5-geodata/worldLow";
import am5themes_Animated from "@amcharts/amcharts5/themes/Animated";

export default {
  name: 'MapContainer',
  mounted() {
    let root = am5.Root.new("globeDiv");

    root.setThemes([
      am5themes_Animated.new(root)
    ]);

    let chart = root.container.children.push(am5map.MapChart.new(root, {
      panX: "rotateX",
      panY: "rotateY",
      projection: am5map.geoOrthographic(),
      paddingBottom: 20,
      paddingTop: 20,
      paddingLeft: 20,
      paddingRight: 20
    }));

    let polygonSeries = chart.series.push(am5map.MapPolygonSeries.new(root, {
      geoJSON: am5geodata_worldLow
    }));

    // Update polygon template for better visuals
    polygonSeries.mapPolygons.template.setAll({
      tooltipText: "{name}",
      toggleKey: "active",
      interactive: true,
      fill: am5.color(0x99c2f2), // A pleasant shade of blue
      stroke: am5.color(0xffffff) // White borders for countries
    });


    polygonSeries.mapPolygons.template.events.on("active", function(active, target) {
      if (target.get("active")) {
        console.log("Clicked on", target.dataItem.get("dataContext").name);
        var centroid = target.geoCentroid();
        if (centroid) {
          chart.animate({ key: "rotationX", to: -centroid.longitude, duration: 1500, easing: am5.ease.inOut(am5.ease.cubic) });
          chart.animate({ key: "rotationY", to: -centroid.latitude, duration: 1500, easing: am5.ease.inOut(am5.ease.cubic) });
        }
      }
    });

    // Keep a reference to clean up when the component unmounts
    this.chart = chart;
    this.root = root;
  },
  beforeUnmount() {
    if (this.root) {
      this.root.dispose();
    }
  }
}
</script>
<style scoped>
.map-container {
  height: 50%; /* Adjust based on your needs */
  width: 100%;
  background-color: #ddedea; /* A light gray that should contrast better with the map */
  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); /* Add some shadow for depth */
  border-radius: 8px; /* Optional: rounded corners for a modern look */
}

/* Additional style adjustments for the amCharts map. */
/* Note: You might need to adjust the selectors based on the actual DOM structure generated by amCharts. */
.amcharts-MapChart, .amcharts-map-polygon-series {
  stroke-width: 1; /* Adjust the border width of countries */
  stroke: #ffffff; /* White borders for the countries for better contrast */
}

.amcharts-map-polygon {
  transition: fill 0.3s; /* Smooth transition for color changes */
}

.amcharts-map-polygon:hover {
  fill: #c0c0c0 !important; /* Highlight color on hover */
}
</style>
